### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by alireza11048** [telekom/sysrepo-plugin-interfaces#28]
Hi, 
i am trying to compile this project, but running "make -j$(nproc) install" command gives me the below error:

> sysrepo-plugin-interfaces/src/routing/routing.c:166:141: error: ‘SR_SUBSCR_CTX_REUSE’ undeclared (first use in this function)       
>   166 |  error = sr_oper_get_items_subscribe(session, BASE_YANG_MODEL, ROUTING_INTERFACE_LEAF_LIST_YANG_PATH, routing_oper_get_interfaces_cb, NULL, SR_SUBSCR_CTX_REUSE, &subscription);

could anyone give me an idea to solve the problem?
thanks in advance

P.S: sysrepocfg --version gives the below result:

> sysrepocfg - sysrepo configuration manipulation tool, compiled with libsysrepo v2.1.64 (SO v7.6.6)

**Comment by feelqah** [comment]
Hi,
The `master` branch is not compatible with your sysrepo version.
You should checkout the `devel` branch. The `master` branch hasn't been updated in a while (we're planning our first release etc. soon).
Sorry for the inconvenience, we'll update the readme in the meantime.
Let me know if you stumble upon any other issues, and we'll fix 'em asap.

**Comment by alireza11048** [comment]
thanks,
switching to the devel branch solved the problem.
