### ISSUE TITLE
Segfault Upon Creation of a Docker Network

### ISSUE THREAD

**Issue by ciaran2** [telekom/sysrepo-plugin-interfaces#33]
Steps to reproduce:

1. Launch sysrepo-plugind with sysrepo-plugin-interfaces.so in plugins directory.
2. Create a docker network via the docker CLI, e.g. `docker network create -d bridge testbridge`
3. sysrepo-plugind exits with the following log messages as seen via systemd:
```
Sep 06 21:07:14 localhost.localdomain sysrepo-plugind[1258]: [INF] No datastore changes to apply.
Sep 06 21:07:31 localhost.localdomain sysrepo-plugind[1258]: [DBG] interfaces-plugin: entered cb function for a link manager
Sep 06 21:07:31 localhost.localdomain systemd[1]: sysrepo-plugind.service: Main process exited, code=killed, status=11/SEGV
Sep 06 21:07:31 localhost.localdomain systemd[1]: sysrepo-plugind.service: Failed with result 'signal'.
```
Segfault does not occur when sysrepo-plugin-interfaces.so is removed from the plugin directory.

**Comment by feelqah** [comment]
Hi,
just pushed a fix on devel for this.
commit:  [a1738f4](https://github.com/telekom/sysrepo-plugin-interfaces/commit/a1738f49114d784c4f4f8f4d26de83ac251b7f27)  

Try again, and let me know if it works now

**Comment by ciaran2** [comment]
Can confirm there is now no crash in this case using current devel code
