### ISSUE TITLE
Is this plugin still mantained?

### ISSUE THREAD

**Issue by safesintesi** [telekom/sysrepo-plugin-interfaces#62]
I was trying o install this plugin and encountered a few issues.
It seems like a ton of development was never merged into `main` and the most active contributor was removed from the repo.
Is there any insight on this? The last issues were not even addressed...
@jvijtiuk @iffy50

**Comment by precla** [comment]
Hi @safesintesi . Unfortunately not. But there will be a new version soon available in a new repository. We'll leave this issue open and when the new version is released we will link here to it

**Comment by precla** [comment]
The following repository contains the interfaces plugin which is now written in C++:

https://github.com/telekom/sysrepo-plugins

This repository "sysrepo-plugin-interfaces" will be soon marked deprecated.

**Comment by safesintesi** [comment]
Hi @precla !
It would be nice to have the link on the readme and archive this repo at this point.
Thanks for the work!
